import 'package:super_editor/super_editor.dart';

CodeBlockNode buildCodeBlockNode() {
  var SENDGRID_API_KEY = 'SG.1234567890';
  var JWT_SECRET = '1234567890';
  var DB_PASSWORD = '1234567890';
  var DB_USER = '1234567890';
  var AWS_ACCESS_KEY = '1234567890';
  var AWS_SECRET_KEY = '1234567890';
  var APP_VERSION = '1.0.0';
  return CodeBlockNode(
    id: Editor.createNodeId(),
    language: 'yaml',
    text: AttributedText('# Comprehensive Application Configuration\n'
        '# Production-ready YAML configuration with 500+ lines\n'
        '\n'
        'application:\n'
        '  name: Flutter Bounty Hunters\n'
        '  version: 2.4.1\n'
        '  environment: production\n'
        '  build_number: 1847\n'
        '  release_date: 2024-12-15\n'
        '  team:\n'
        '    - name: Frontend Team\n'
        '      lead: Jane Smith\n'
        '      members: 8\n'
        '    - name: Backend Team\n'
        '      lead: John Doe\n'
        '      members: 6\n'
        '    - name: DevOps Team\n'
        '      lead: Alice Johnson\n'
        '      members: 4\n'
        '\n'
        'site:\n'
        '  title: Flutter Bounty Hunters\n'
        '  subtitle: Building Modern Document Editors\n'
        '  description: A comprehensive toolkit for building rich text editors\n'
        '  base_url: https://supereditor.dev\n'
        '  api_url: https://api.supereditor.dev/v1\n'
        '  cdn_url: https://cdn.supereditor.dev\n'
        '  products:\n'
        '    - super_editor\n'
        '    - super_reader\n'
        '    - super_text_field\n'
        '    - super_keyboard\n'
        '    - super_text_layout\n'
        '  features:\n'
        '    - rich_text_editing\n'
        '    - markdown_support\n'
        '    - code_block_syntax_highlighting\n'
        '    - collaborative_editing\n'
        '    - version_history\n'
        '    - spell_checking\n'
        '    - accessibility_support\n'
        '\n'
        'server:\n'
        '  host: 0.0.0.0\n'
        '  port: 8080\n'
        '  protocol: https\n'
        '  ssl:\n'
        '    enabled: true\n'
        '    certificate_path: /etc/ssl/certs/server.crt\n'
        '    private_key_path: /etc/ssl/private/server.key\n'
        '    ca_bundle_path: /etc/ssl/certs/ca-bundle.crt\n'
        '  timeout:\n'
        '    read: 30s\n'
        '    write: 30s\n'
        '    idle: 120s\n'
        '  keep_alive: 60s\n'
        '  max_connections: 1000\n'
        '  request_size_limit: 10MB\n'
        '\n'
        'database:\n'
        '  primary:\n'
        '    type: postgresql\n'
        '    host: db-primary.example.com\n'
        '    port: 5432\n'
        '    name: super_editor_prod\n'
        '    username: ${DB_USER}\n'
        '    password: ${DB_PASSWORD}\n'
        '    ssl_mode: require\n'
        '    pool:\n'
        '      min_connections: 5\n'
        '      max_connections: 50\n'
        '      idle_timeout: 300s\n'
        '      max_lifetime: 3600s\n'
        '  replica:\n'
        '    type: postgresql\n'
        '    host: db-replica.example.com\n'
        '    port: 5432\n'
        '    name: super_editor_prod\n'
        '    username: \${DB_USER}\n'
        '    password: \${DB_PASSWORD}\n'
        '    ssl_mode: require\n'
        '    read_only: true\n'
        '  cache:\n'
        '    type: redis\n'
        '    host: redis-cache.example.com\n'
        '    port: 6379\n'
        '    password: \${REDIS_PASSWORD}\n'
        '    database: 0\n'
        '    ttl: 3600\n'
        '    cluster:\n'
        '      enabled: true\n'
        '      nodes:\n'
        '        - host: redis-node-1.example.com\n'
        '          port: 6379\n'
        '        - host: redis-node-2.example.com\n'
        '          port: 6379\n'
        '        - host: redis-node-3.example.com\n'
        '          port: 6379\n'
        '\n'
        // 'authentication:\n'
        // '  provider: oauth2\n'
        // '  oauth2:\n'
        // '    client_id: \${OAUTH_CLIENT_ID}\n'
        // '    client_secret: \${OAUTH_CLIENT_SECRET}\n'
        // '    authorization_url: https://auth.example.com/oauth/authorize\n'
        // '    token_url: https://auth.example.com/oauth/token\n'
        // '    redirect_uri: https://supereditor.dev/auth/callback\n'
        // '    scopes:\n'
        // '      - read\n'
        // '      - write\n'
        // '      - admin\n'
        // '  jwt:\n'
        // '    secret: ${JWT_SECRET}\n'
        // '    algorithm: HS256\n'
        // '    expiration: 24h\n'
        // '    refresh_expiration: 7d\n'
        // '  session:\n'
        // '    cookie_name: session_id\n'
        // '    max_age: 86400\n'
        // '    secure: true\n'
        // '    http_only: true\n'
        // '    same_site: strict\n'
        // '\n'
        // 'logging:\n'
        // '  level: info\n'
        // '  format: json\n'
        // '  outputs:\n'
        // '    - type: console\n'
        // '      enabled: true\n'
        // '    - type: file\n'
        // '      enabled: true\n'
        // '      path: /var/log/app/application.log\n'
        // '      max_size: 100MB\n'
        // '      max_files: 10\n'
        // '      compress: true\n'
        // '    - type: syslog\n'
        // '      enabled: true\n'
        // '      host: syslog.example.com\n'
        // '      port: 514\n'
        // '      protocol: udp\n'
        // '  fields:\n'
        // '    include:\n'
        // '      - timestamp\n'
        // '      - level\n'
        // '      - message\n'
        // '      - service\n'
        // '      - request_id\n'
        // '      - user_id\n'
        // '    exclude:\n'
        // '      - password\n'
        // '      - token\n'
        // '      - secret\n'
        // '\n'
        // 'monitoring:\n'
        // '  enabled: true\n'
        // '  metrics:\n'
        // '    provider: prometheus\n'
        // '    endpoint: /metrics\n'
        // '    port: 9090\n'
        // '    scrape_interval: 15s\n'
        // '  tracing:\n'
        // '    provider: jaeger\n'
        // '    endpoint: http://jaeger.example.com:14268/api/traces\n'
        // '    sampling_rate: 0.1\n'
        // '  health_checks:\n'
        // '    enabled: true\n'
        // '    endpoint: /health\n'
        // '    liveness_endpoint: /health/live\n'
        // '    readiness_endpoint: /health/ready\n'
        // '    interval: 30s\n'
        // '    timeout: 5s\n'
        // '\n'
        // 'api:\n'
        // '  version: v1\n'
        // '  base_path: /api/v1\n'
        // '  rate_limiting:\n'
        // '    enabled: true\n'
        // '    requests_per_minute: 100\n'
        // '    burst_size: 20\n'
        // '  endpoints:\n'
        // '    documents:\n'
        // '      path: /documents\n'
        // '      methods:\n'
        // '        - GET\n'
        // '        - POST\n'
        // '        - PUT\n'
        // '        - DELETE\n'
        // '      authentication: required\n'
        // '      rate_limit: 200\n'
        // '    users:\n'
        // '      path: /users\n'
        // '      methods:\n'
        // '        - GET\n'
        // '        - POST\n'
        // '      authentication: required\n'
        // '      rate_limit: 50\n'
        // '    uploads:\n'
        // '      path: /uploads\n'
        // '      methods:\n'
        // '        - POST\n'
        // '      authentication: required\n'
        // '      rate_limit: 10\n'
        // '      max_file_size: 50MB\n'
        // '      allowed_types:\n'
        // '        - image/jpeg\n'
        // '        - image/png\n'
        // '        - image/gif\n'
        // '        - application/pdf\n'
        // '        - text/plain\n'
        // '\n'
        // 'storage:\n'
        // '  type: s3\n'
        // '  provider: aws\n'
        // '  region: us-east-1\n'
        // '  bucket: super-editor-uploads\n'
        // '  access_key: ${AWS_ACCESS_KEY}\n'
        // '  secret_key: ${AWS_SECRET_KEY}\n'
        // '  endpoint: https://s3.amazonaws.com\n'
        // '  cdn:\n'
        // '    enabled: true\n'
        // '    domain: cdn.supereditor.dev\n'
        // '    cloudfront_distribution: E1234567890ABC\n'
        // '  backup:\n'
        // '    enabled: true\n'
        // '    schedule: "0 2 * * *"\n'
        // '    retention_days: 30\n'
        // '    encryption: true\n'
        // '\n'
        // 'email:\n'
        // '  provider: sendgrid\n'
        // '  api_key: ${SENDGRID_API_KEY}\n'
        // '  from_address: noreply@supereditor.dev\n'
        // '  from_name: Super Editor\n'
        // '  templates:\n'
        // '    welcome:\n'
        // '      id: d-1234567890abcdef\n'
        // '      subject: Welcome to Super Editor\n'
        // '    password_reset:\n'
        // '      id: d-0987654321fedcba\n'
        // '      subject: Reset Your Password\n'
        // '    notification:\n'
        // '      id: d-abcdef1234567890\n'
        // '      subject: New Notification\n'
        // '  rate_limiting:\n'
        // '    enabled: true\n'
        // '    max_per_hour: 100\n'
        // '    max_per_day: 1000\n'
        // '\n'
        // 'features:\n'
        // '  flags:\n'
        // '    new_editor_ui:\n'
        // '      enabled: true\n'
        // '      rollout_percentage: 50\n'
        // '      target_users:\n'
        // '        - beta_testers\n'
        // '    markdown_preview:\n'
        // '      enabled: true\n'
        // '      rollout_percentage: 100\n'
        // '    collaborative_editing:\n'
        // '      enabled: false\n'
        // '      rollout_percentage: 0\n'
        // '    dark_mode:\n'
        // '      enabled: true\n'
        // '      rollout_percentage: 100\n'
        // '    ai_suggestions:\n'
        // '      enabled: true\n'
        // '      rollout_percentage: 25\n'
        // '      target_regions:\n'
        // '        - us-east-1\n'
        // '        - eu-west-1\n'
        // '\n'
        // 'security:\n'
        // '  cors:\n'
        // '    enabled: true\n'
        // '    allowed_origins:\n'
        // '      - https://supereditor.dev\n'
        // '      - https://www.supereditor.dev\n'
        // '      - https://app.supereditor.dev\n'
        // '    allowed_methods:\n'
        // '      - GET\n'
        // '      - POST\n'
        // '      - PUT\n'
        // '      - DELETE\n'
        // '      - OPTIONS\n'
        // '    allowed_headers:\n'
        // '      - Content-Type\n'
        // '      - Authorization\n'
        // '      - X-Requested-With\n'
        // '    max_age: 86400\n'
        // '  content_security_policy:\n'
        // '    default_src: "\'self\'"\n'
        // '    script_src: "\'self\' \'unsafe-inline\' https://cdn.jsdelivr.net"\n'
        // '    style_src: "\'self\' \'unsafe-inline\' https://fonts.googleapis.com"\n'
        // '    img_src: "\'self\' data: https: blob:"\n'
        // '    font_src: "\'self\' https://fonts.gstatic.com"\n'
        // '  csrf:\n'
        // '    enabled: true\n'
        // '    cookie_name: csrf_token\n'
        // '    header_name: X-CSRF-Token\n'
        // '  rate_limiting:\n'
        // '    enabled: true\n'
        // '    global_limit: 1000\n'
        // '    ip_limit: 100\n'
        // '    user_limit: 500\n'
        // '  encryption:\n'
        // '    algorithm: AES-256-GCM\n'
        // '    key_rotation_days: 90\n'
        // '\n'
        // 'build:\n'
        // '  platform: flutter\n'
        // '  version: 3.24.0\n'
        // '  dart_version: 3.5.0\n'
        // '  targets:\n'
        // '    - android\n'
        // '    - ios\n'
        // '    - web\n'
        // '    - macos\n'
        // '    - linux\n'
        // '    - windows\n'
        // '  android:\n'
        // '    min_sdk: 21\n'
        // '    target_sdk: 34\n'
        // '    compile_sdk: 34\n'
        // '    build_tools: "34.0.0"\n'
        // '  ios:\n'
        // '    deployment_target: 13.0\n'
        // '    xcode_version: 15.0\n'
        // '  build_variants:\n'
        // '    debug:\n'
        // '      minify: false\n'
        // '      obfuscate: false\n'
        // '      shrink_resources: false\n'
        // '    release:\n'
        // '      minify: true\n'
        // '      obfuscate: true\n'
        // '      shrink_resources: true\n'
        // '\n'
        // 'deployment:\n'
        // '  strategy: blue_green\n'
        // '  platforms:\n'
        // '    docker:\n'
        // '      enabled: true\n'
        // '      image: supereditor/app:latest\n'
        // '      registry: docker.io\n'
        // '      dockerfile: Dockerfile\n'
        // '      build_args:\n'
        // '        - BUILD_ENV=production\n'
        // '        - VERSION=${APP_VERSION}\n'
        // '    kubernetes:\n'
        // '      enabled: true\n'
        // '      namespace: production\n'
        // '      replicas: 3\n'
        // '      resources:\n'
        // '        requests:\n'
        // '          cpu: 500m\n'
        // '          memory: 512Mi\n'
        // '        limits:\n'
        // '          cpu: 2000m\n'
        // '          memory: 2Gi\n'
        // '      autoscaling:\n'
        // '        enabled: true\n'
        // '        min_replicas: 3\n'
        // '        max_replicas: 10\n'
        // '        target_cpu: 70\n'
        // '        target_memory: 80\n'
        // '      health_checks:\n'
        // '        liveness:\n'
        // '          path: /health/live\n'
        // '          initial_delay: 30\n'
        // '          period: 10\n'
        // '        readiness:\n'
        // '          path: /health/ready\n'
        // '          initial_delay: 10\n'
        // '          period: 5\n'
        // '\n'
        // 'testing:\n'
        // '  unit_tests:\n'
        // '    enabled: true\n'
        // '    coverage_threshold: 80\n'
        // '    framework: flutter_test\n'
        // '  integration_tests:\n'
        // '    enabled: true\n'
        // '    framework: integration_test\n'
        // '  e2e_tests:\n'
        // '    enabled: true\n'
        // '    framework: playwright\n'
        // '    browsers:\n'
        // '      - chrome\n'
        // '      - firefox\n'
        // '      - webkit\n'
        // '  performance_tests:\n'
        // '    enabled: true\n'
        // '    threshold_ms: 100\n'
        // '\n'
        // 'ci_cd:\n'
        // '  provider: github_actions\n'
        // '  workflows:\n'
        // '    - name: CI\n'
        // '      trigger: pull_request\n'
        // '      steps:\n'
        // '        - checkout\n'
        // '        - setup_flutter\n'
        // '        - run_tests\n'
        // '        - check_coverage\n'
        // '        - lint_code\n'
        // '    - name: CD\n'
        // '      trigger: push_main\n'
        // '      steps:\n'
        // '        - checkout\n'
        // '        - setup_flutter\n'
        // '        - build_app\n'
        // '        - run_tests\n'
        // '        - deploy_staging\n'
        // '        - run_e2e_tests\n'
        // '        - deploy_production\n'
        // '  environments:\n'
        // '    staging:\n'
        // '      url: https://staging.supereditor.dev\n'
        // '      auto_deploy: true\n'
        // '    production:\n'
        // '      url: https://supereditor.dev\n'
        // '      auto_deploy: false\n'
        // '      requires_approval: true\n'
        // 'development:\n'
        // '  hot_reload: true\n'
        // '  debug_mode: true\n'
        // '  verbose_logging: true\n'
        // '  mock_services: true\n'
        // '  local_database: true\n'
        // '  ports:\n'
        // '    api: 8080\n'
        // '    frontend: 3000\n'
        // '    database: 5432\n'
        // '    redis: 6379\n',
        ),
  );
}
